package maichess.engine.domain

import maichess.engine.domain.TimingStrategy.*
import maichess.engine.domain.EngineVariant.*

object BotRegistry:

  val all: List[BotConfig] = List(

    // ── Tier 1 (Base) bots — bitboard alpha-beta ──────────────────────────────

    BotConfig(
      id          = "bullet",
      name        = "Bullet",
      elo         = 1400,
      strategy    = Fixed(100L),
      variant     = Base,
      description = "A fully-featured bitboard engine that represents the board as packed 64-bit integers and analyses all pieces simultaneously using hardware instructions. A transposition table ensures positions are never evaluated twice, and captures are followed beyond the main search depth to prevent horizon blunders. Allocates a flat 100 ms per move — fast and instinctive.",
    ),
    BotConfig(
      id          = "bullet_proportional",
      name        = "Bullet Proportional",
      elo         = 1400,
      strategy    = Proportional(divisor = 40, minMs = 50L, fallbackMs = 100L),
      variant     = Base,
      description = "A fully-featured bitboard engine with transposition table and quiescence search. Distributes its remaining time proportionally across the estimated moves left in the game — a more clock-aware approach than a fixed allocation.",
    ),
    BotConfig(
      id          = "bullet_aggressive",
      name        = "Bullet Aggressive",
      elo         = 1400,
      strategy    = Aggressive(fraction = 0.07, minMs = 50L, fallbackMs = 100L),
      variant     = Base,
      description = "A fully-featured bitboard engine with transposition table and quiescence search. Spends 7% of remaining time per move, front-loading calculation into the early game where move choices are most consequential.",
    ),
    BotConfig(
      id          = "blitz",
      name        = "Blitz",
      elo         = 1700,
      strategy    = Fixed(1000L),
      variant     = Base,
      description = "A fully-featured bitboard engine using magic bitboards for instant sliding-piece attack lookup and a transposition table to avoid repeated work. With 1 second per move it reaches depths where it reliably handles basic tactics and applies positional pressure. A solid club-player level opponent.",
    ),
    BotConfig(
      id          = "blitz_proportional",
      name        = "Blitz Proportional",
      elo         = 1700,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = Base,
      description = "A fully-featured bitboard engine at blitz speed. Proportional time management means it invests its clock across the whole game, allocating roughly equal time per phase rather than rushing in the endgame.",
    ),
    BotConfig(
      id          = "blitz_aggressive",
      name        = "Blitz Aggressive",
      elo         = 1700,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = Base,
      description = "A fully-featured bitboard engine at blitz speed. Uses 6% of remaining time per move — thinking most in the opening and middlegame, then playing quicker as the position simplifies.",
    ),
    BotConfig(
      id          = "classical",
      name        = "Classical",
      elo         = 2000,
      strategy    = Fixed(5000L),
      variant     = Base,
      description = "The bitboard engine at its most patient: 5 seconds per move allows significantly deeper searches than the blitz variant. Capable of finding multi-move combinations and applying coherent positional pressure across the whole game. A strong club-level opponent.",
    ),
    BotConfig(
      id          = "classical_proportional",
      name        = "Classical Proportional",
      elo         = 2000,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = Base,
      description = "The bitboard engine at classical pace with proportional time management. Adapts how long it thinks based on game progress — a thoughtful, clock-aware engine that never rushes the endgame.",
    ),
    BotConfig(
      id          = "classical_aggressive",
      name        = "Classical Aggressive",
      elo         = 2000,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = Base,
      description = "The bitboard engine at classical pace. Spends 5% of remaining time per move — a front-loaded approach that ensures its deepest thinking happens in the most critical phases of the game.",
    ),

    // ── Tier 0 (Basic) bots — mailbox minimax, no bitboards ──────────────────

    BotConfig(
      id          = "basic_bullet",
      name        = "Basic Bullet",
      elo         = 700,
      strategy    = Fixed(100L),
      variant     = Basic,
      description = "A bare-bones engine that sees chess purely as material on a board. No bitboards, no position memory, no move ordering — just brute-force minimax with plain material counting. Allocates a flat 100 ms per move, making every decision as fast and honest as possible.",
    ),
    BotConfig(
      id          = "basic_bullet_prop",
      name        = "Basic Bullet Prop",
      elo         = 700,
      strategy    = Proportional(divisor = 40, minMs = 50L, fallbackMs = 100L),
      variant     = Basic,
      description = "A bare-bones engine that sees chess purely as material on a board. No bitboards, no position memory, no move ordering — just brute-force minimax with plain material counting. Divides remaining time proportionally across expected moves remaining so it never burns the clock early.",
    ),
    BotConfig(
      id          = "basic_bullet_aggr",
      name        = "Basic Bullet Aggressive",
      elo         = 700,
      strategy    = Aggressive(fraction = 0.07, minMs = 50L, fallbackMs = 100L),
      variant     = Basic,
      description = "A bare-bones engine that sees chess purely as material on a board. No bitboards, no position memory, no move ordering — just brute-force minimax with plain material counting. Spends 7% of remaining time per move, front-loading calculation into the opening and thinning out as the game nears its end.",
    ),
    BotConfig(
      id          = "basic_blitz",
      name        = "Basic Blitz",
      elo         = 800,
      strategy    = Fixed(1000L),
      variant     = Basic,
      description = "The simplest engine in the roster — a plain 8×8 board array with material-only evaluation and no position memory. Without a transposition table it re-analyses the same positions repeatedly, but 1 second per move lets it reach a few extra plies of depth, making it a small but visible step up in tactical sharpness.",
    ),
    BotConfig(
      id          = "basic_blitz_prop",
      name        = "Basic Blitz Prop",
      elo         = 800,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = Basic,
      description = "The simplest engine in the roster — a plain 8×8 board array with material-only evaluation and no position memory. Spreads its clock evenly across the game, adapting move time to how many moves it estimates are left.",
    ),
    BotConfig(
      id          = "basic_blitz_aggr",
      name        = "Basic Blitz Aggressive",
      elo         = 800,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = Basic,
      description = "The simplest engine in the roster — a plain 8×8 board array with material-only evaluation and no position memory. Uses 6% of remaining time per move — a middle ground between consistent pacing and front-loaded thinking.",
    ),
    BotConfig(
      id          = "basic_classical",
      name        = "Basic Classical",
      elo         = 900,
      strategy    = Fixed(5000L),
      variant     = Basic,
      description = "The bare-bones engine at its most patient: 5 seconds per move lets it reach its deepest searches, but the lack of position memory and primitive evaluation still cap its strength well below club level. A good starting opponent for beginners or anyone curious about how much modern optimisations actually matter.",
    ),
    BotConfig(
      id          = "basic_classical_prop",
      name        = "Basic Classical Prop",
      elo         = 900,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = Basic,
      description = "The bare-bones engine at its most patient. Distributes its clock proportionally — in a typical game it invests roughly 5 seconds per move, with the flexibility to think longer if fewer moves remain, avoiding any risk of running out of time.",
    ),
    BotConfig(
      id          = "basic_classical_aggr",
      name        = "Basic Classical Aggr",
      elo         = 900,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = Basic,
      description = "The bare-bones engine at its most patient. Spends 5% of remaining time each move, which at the start of a fresh game amounts to about 5 seconds — comparable to the fixed variant but with a natural taper as the clock runs down.",
    ),

    // ── Tier 2 (EnhancedSearch) bots — LMR + null-move pruning + PVS ──────────

    BotConfig(
      id          = "search_bullet",
      name        = "Search Bullet",
      elo         = 1600,
      strategy    = Fixed(100L),
      variant     = EnhancedSearch,
      description = "Adds three high-impact search techniques to the bitboard engine: Late Move Reductions cut depth on moves likely to be bad, Null Move Pruning prunes subtrees where even passing a turn beats the opponent, and Principal Variation Search confirms the best move with a narrow re-search window. Together they roughly double effective search depth at the same time budget. Fixed at 100 ms per move.",
    ),
    BotConfig(
      id          = "search_bullet_prop",
      name        = "Search Bullet Prop",
      elo         = 1600,
      strategy    = Proportional(divisor = 40, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedSearch,
      description = "LMR, Null Move Pruning, and PVS layered on the bitboard engine roughly double effective search depth compared to the base tier. Allocates time proportionally — spreading the clock across estimated remaining moves so it never wastes it in a long game or rushes in a short one.",
    ),
    BotConfig(
      id          = "search_bullet_aggr",
      name        = "Search Bullet Aggressive",
      elo         = 1600,
      strategy    = Aggressive(fraction = 0.07, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedSearch,
      description = "LMR, Null Move Pruning, and PVS layered on the bitboard engine roughly double effective search depth. Spends 7% of remaining time per move, investing more in the opening where decisions carry the most weight.",
    ),
    BotConfig(
      id          = "search_blitz",
      name        = "Search Blitz",
      elo         = 1900,
      strategy    = Fixed(1000L),
      variant     = EnhancedSearch,
      description = "With 1 second and all three search enhancements active, this bot reaches depths where it begins to uncover complex middlegame tactics the base engine misses entirely. LMR, Null Move Pruning, and PVS together mean it wastes very little effort on bad moves.",
    ),
    BotConfig(
      id          = "search_blitz_prop",
      name        = "Search Blitz Prop",
      elo         = 1900,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedSearch,
      description = "LMR, Null Move Pruning, and PVS layered on the bitboard engine, with proportional time management. The bot adapts how long it thinks based on the game's progress, spending its clock where it matters most.",
    ),
    BotConfig(
      id          = "search_blitz_aggr",
      name        = "Search Blitz Aggressive",
      elo         = 1900,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedSearch,
      description = "LMR, Null Move Pruning, and PVS layered on the bitboard engine. Spends 6% of remaining time per move — strong and deliberate in the opening and middlegame, quicker as the endgame simplifies.",
    ),
    BotConfig(
      id          = "search_classical",
      name        = "Search Classical",
      elo         = 2150,
      strategy    = Fixed(5000L),
      variant     = EnhancedSearch,
      description = "At 5 seconds per move with LMR, Null Move Pruning, and PVS active, this bot reaches search depths that would take the base engine several times longer to achieve. Expect sharp tactical awareness and consistent middlegame pressure — a challenging opponent for club-level players.",
    ),
    BotConfig(
      id          = "search_classical_prop",
      name        = "Search Classical Prop",
      elo         = 2150,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedSearch,
      description = "At full depth with all three search enhancements, this bot invests its time proportionally — roughly 5 seconds per move in a standard game, with flexibility to think longer if fewer moves remain.",
    ),
    BotConfig(
      id          = "search_classical_aggr",
      name        = "Search Classical Aggr",
      elo         = 2150,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedSearch,
      description = "At full depth with LMR, Null Move Pruning, and PVS, this bot spends 5% of remaining time each move — front-loaded thinking in the opening, faster play as the position simplifies. Consistent tactical sharpness throughout the game.",
    ),

    // ── Tier 3 (EnhancedOrdering) bots — killers + history + SEE + aspiration + check extensions ──

    BotConfig(
      id          = "ordering_bullet",
      name        = "Ordering Bullet",
      elo         = 1750,
      strategy    = Fixed(100L),
      variant     = EnhancedOrdering,
      description = "Extends the enhanced search engine with five move-ordering improvements: killer moves remember tactics that recently caused cutoffs; history scores track which quiet moves are statistically strong; SEE-based capture ordering evaluates full exchange sequences rather than just piece values; aspiration windows narrow the search between iterations; and check extensions follow tactical check chains deeper. More pruning in the same time means more depth. Fixed at 100 ms per move.",
    ),
    BotConfig(
      id          = "ordering_bullet_prop",
      name        = "Ordering Bullet Prop",
      elo         = 1750,
      strategy    = Proportional(divisor = 40, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedOrdering,
      description = "Five move-ordering enhancements — killers, history heuristic, SEE captures, aspiration windows, and check extensions — make every node of the search count. Proportional time allocation keeps the clock balanced across the game.",
    ),
    BotConfig(
      id          = "ordering_bullet_aggr",
      name        = "Ordering Bullet Aggressive",
      elo         = 1750,
      strategy    = Aggressive(fraction = 0.07, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedOrdering,
      description = "Five move-ordering enhancements — killers, history heuristic, SEE captures, aspiration windows, and check extensions — compound to reduce wasted search effort dramatically. Spends 7% of remaining time per move, investing most heavily in the opening and middlegame.",
    ),
    BotConfig(
      id          = "ordering_blitz",
      name        = "Ordering Blitz",
      elo         = 2050,
      strategy    = Fixed(1000L),
      variant     = EnhancedOrdering,
      description = "With 1 second and all five ordering improvements active, this bot's search reaches depths where it reliably finds multi-move combinations that simpler tiers miss. Killer moves and history scores mean it rarely spends time on obviously bad moves.",
    ),
    BotConfig(
      id          = "ordering_blitz_prop",
      name        = "Ordering Blitz Prop",
      elo         = 2050,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedOrdering,
      description = "All five move-ordering improvements with proportional time management. The bot adjusts its thinking time based on the game's progress, spending wisely across the expected remaining moves.",
    ),
    BotConfig(
      id          = "ordering_blitz_aggr",
      name        = "Ordering Blitz Aggressive",
      elo         = 2050,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedOrdering,
      description = "All five move-ordering improvements with an aggressive 6% time fraction. Thinks hardest in the opening and middlegame where the ordering enhancements deliver the biggest benefit.",
    ),
    BotConfig(
      id          = "ordering_classical",
      name        = "Ordering Classical",
      elo         = 2300,
      strategy    = Fixed(5000L),
      variant     = EnhancedOrdering,
      description = "Given 5 seconds with all move-ordering enhancements, this is one of the strongest search-only bots in the roster. It rarely overlooks tactical opportunities and handles positional manoeuvring with notable consistency. A serious opponent for intermediate-to-advanced club players.",
    ),
    BotConfig(
      id          = "ordering_classical_prop",
      name        = "Ordering Classical Prop",
      elo         = 2300,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedOrdering,
      description = "Five seconds of enhanced-ordering search, distributed proportionally. This bot manages its clock carefully, ensuring it always has time to think without wasting it in simplified endgames.",
    ),
    BotConfig(
      id          = "ordering_classical_aggr",
      name        = "Ordering Classical Aggr",
      elo         = 2300,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedOrdering,
      description = "Five seconds of enhanced-ordering search, spent at 5% of remaining time per move. Front-loads its strongest thinking into the critical phases of the game, then plays more quickly as positions simplify.",
    ),

    // ── Tier 4 (EnhancedEval) bots — king safety, pawn structure, full mobility ──

    BotConfig(
      id          = "eval_bullet",
      name        = "Eval Bullet",
      elo         = 1900,
      strategy    = Fixed(100L),
      variant     = EnhancedEval,
      description = "The ordering-tier search engine now paired with a richer positional evaluation: king safety (exposed kings are penalised), pawn structure (doubled, isolated, and passed pawns with rank-scaled bonuses), rook placement bonuses (open files, 7th rank), and full mobility evaluation for all pieces. All terms taper smoothly between opening and endgame. Tactically sharp and positionally aware — a challenging opponent even for strong club players. Fixed at 100 ms per move.",
    ),
    BotConfig(
      id          = "eval_bullet_prop",
      name        = "Eval Bullet Prop",
      elo         = 1900,
      strategy    = Proportional(divisor = 40, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedEval,
      description = "Rich positional evaluation — king safety, pawn structure, rook bonuses, and full piece mobility — layered on top of the enhanced-ordering search. Proportional time allocation keeps its clock balanced across the game.",
    ),
    BotConfig(
      id          = "eval_bullet_aggr",
      name        = "Eval Bullet Aggressive",
      elo         = 1900,
      strategy    = Aggressive(fraction = 0.07, minMs = 50L, fallbackMs = 100L),
      variant     = EnhancedEval,
      description = "Rich positional evaluation layered on top of the enhanced-ordering search. Spends 7% of remaining time per move, thinking hardest in the opening and middlegame where positional understanding matters most.",
    ),
    BotConfig(
      id          = "eval_blitz",
      name        = "Eval Blitz",
      elo         = 2200,
      strategy    = Fixed(1000L),
      variant     = EnhancedEval,
      description = "With 1 second and a full positional model, this bot plays in a recognisably strategic way: it prefers castled kings, connected pawns, active rooks, and mobile pieces — not just short-term tactics. A significant step up from simpler tiers at the same time control.",
    ),
    BotConfig(
      id          = "eval_blitz_prop",
      name        = "Eval Blitz Prop",
      elo         = 2200,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedEval,
      description = "Full positional model with proportional time management. The bot adapts its thinking time to the game's rhythm, allocating more when positions are complex and less when play is straightforward.",
    ),
    BotConfig(
      id          = "eval_blitz_aggr",
      name        = "Eval Blitz Aggressive",
      elo         = 2200,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = EnhancedEval,
      description = "Full positional model with an aggressive time fraction — invests 6% of remaining time per move. Plays its most deliberate, strategically rich chess in the opening and early middlegame.",
    ),
    BotConfig(
      id          = "eval_classical",
      name        = "Eval Classical",
      elo         = 2450,
      strategy    = Fixed(5000L),
      variant     = EnhancedEval,
      description = "Given 5 seconds with the complete evaluation model, this bot plays at a strong amateur level. It handles king safety, pawn breaks, rook activation, and piece coordination in a coherent, strategic style. The strongest evaluation-based bot in the roster — tough for most club players.",
    ),
    BotConfig(
      id          = "eval_classical_prop",
      name        = "Eval Classical Prop",
      elo         = 2450,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedEval,
      description = "Five seconds with the full positional evaluation, distributed proportionally. A deeply strategic bot that manages its time intelligently across the whole game.",
    ),
    BotConfig(
      id          = "eval_classical_aggr",
      name        = "Eval Classical Aggr",
      elo         = 2450,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = EnhancedEval,
      description = "Five seconds with the full positional evaluation, spending 5% of remaining time per move. Plays its most strategically profound chess early, then simplifies efficiently as the endgame approaches.",
    ),

    // ── Tier 5 (Knowledge) bots — opening book + endgame tablebase probing ──

    BotConfig(
      id          = "knowledge_blitz",
      name        = "Knowledge Blitz",
      elo         = 2350,
      strategy    = Fixed(1000L),
      variant     = Knowledge,
      description = "The strongest tier, augmented with two pre-computed databases. In the opening, a professional opening book provides theory-correct moves instantly, conserving search time for the critical middlegame. When the board simplifies to seven or fewer pieces, a tablebase query delivers provably perfect play — win, draw, or loss is known with certainty, along with exactly how many moves it will take. Fixed at 1 second per move with expert-level knowledge at both ends of the game.",
    ),
    BotConfig(
      id          = "knowledge_blitz_prop",
      name        = "Knowledge Blitz Prop",
      elo         = 2350,
      strategy    = Proportional(divisor = 30, minMs = 200L, fallbackMs = 1000L),
      variant     = Knowledge,
      description = "Opening book in the early moves, endgame tablebase perfection when pieces come off the board, and the full positional evaluation engine in between. Proportional time allocation lets it invest saved opening time into the complex middlegame where thinking matters most.",
    ),
    BotConfig(
      id          = "knowledge_blitz_aggr",
      name        = "Knowledge Blitz Aggressive",
      elo         = 2350,
      strategy    = Aggressive(fraction = 0.06, minMs = 200L, fallbackMs = 1000L),
      variant     = Knowledge,
      description = "Opening book in the first moves, tablebase certainty in the endgame, and an aggressive 6% time fraction through the middlegame. Plays its best chess in the phases where good decisions are hardest to find.",
    ),
    BotConfig(
      id          = "knowledge_classical",
      name        = "Knowledge Classical",
      elo         = 2600,
      strategy    = Fixed(5000L),
      variant     = Knowledge,
      description = "The pinnacle of the roster. Five seconds per move with an opening book, endgame tablebases (provably perfect for up to 7 pieces), and the full evaluation and ordering stack beneath. Plays theory-correct openings, converts middlegame advantages with strategic precision, and closes endgames without error. Appropriate for advanced club players and above.",
    ),
    BotConfig(
      id          = "knowledge_classical_prop",
      name        = "Knowledge Classical Prop",
      elo         = 2600,
      strategy    = Proportional(divisor = 25, minMs = 500L, fallbackMs = 5000L),
      variant     = Knowledge,
      description = "The pinnacle of the roster: opening book, endgame tablebases, full positional evaluation, and proportional time management. Saves time where it can — book moves are instant — and invests it where it counts, in the complex middlegame.",
    ),
    BotConfig(
      id          = "knowledge_classical_aggr",
      name        = "Knowledge Classical Aggr",
      elo         = 2600,
      strategy    = Aggressive(fraction = 0.05, minMs = 500L, fallbackMs = 5000L),
      variant     = Knowledge,
      description = "The pinnacle of the roster: opening book, endgame tablebases, full positional evaluation, and an aggressive 5% time fraction. Plays most deliberately in the opening and middlegame; relies on tablebase certainty to close endgames without spending the clock.",
    ),
  )

  def find(id: String): Option[BotConfig] = all.find(_.id == id)
